---
- name: Setup NGINX Server
  hosts: localhost
  remote_user: ubuntu
  become: yes
  tasks:

  - name: Basically "apt-get update"
    apt:
      update_cache: yes

  - name: Install NGINX Packages
    apt:
      name: nginx
      state: latest

  - name: Update worker_connections value
    lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '^(\s*worker_connections\s*)\d+;'
      line: 'worker_connections {{ new_worker_connections }};'
    vars:
      new_worker_connections: 1000

  - name: Run Docker Container
    docker_container:
      name: my-nginx-container
      image:  "aamir335/nginx:{{ imagename }}"
      state: started
      ports:
      - "80:80"
      
      

  
